server:
  port: 8000

spring:
  application:
    name: CATCHY

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout : 6000ms # 연결 타임아웃
      lettuce:
        pool:
          max-active: 10  # 최대 활성 연결 수
          max-idle: 5  # 최대 유휴 연결 수
          min-idle: 1  # 최소 유휴 연결 수
          max-wait: 2000ms  # 최대 대기 시간
  cloud:
    aws:
      s3:
        bucket: catchy-s3-bucket
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      cloudfront:
        domain: ${CLOUDFRONT_URL}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: >
    com.sixmycat.catchy.feature.block.query.dto,
    com.sixmycat.catchy.feature.feed.query.dto.response,
    com.sixmycat.catchy.feature.follow.query.dto,
    com.sixmycat.catchy.feature.game.query.dto,
    com.sixmycat.catchy.feature.jjure.query.dto,
    com.sixmycat.catchy.feature.like.query.dto,
    com.sixmycat.catchy.feature.member.query.dto,
    com.sixmycat.catchy.feature.notify.query.dto
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

image:
  image-dir: ${IMAGE_DIR}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /v3/api-docs

pagehelper:
  helper-dialect: mariadb
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



